version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always
    env_file:
      - .env

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: /run/secrets/MYSQL_ROOT_PASSWORD
        DB_USER: ${DB_USER}
        DB_PASS: /run/secrets/db_password
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        ADM_PASS: /run/secrets/ADM_PASS
        MYSQL_ROOT_PASSWORD: /run/secrets/MYSQL_ROOT_PASSWORD
        WP_USER_PASS: /run/secrets/WP_USER_PASS
        DB_PASS: /run/secrets/db_password
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always
    env_file:
      - .env
volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mariadb
secrets:
  DB_PASS:
    file: ../secrets/db_password.txt
  MYSQL_ROOT_PASSWORD:
    file: ../secrets/db_root_password.txt
  ADM_PASS:
    file: ../secrets/adm_pass.txt
  WP_USER_PASS:
    file: ../secrets/wp_pass.txt
networks:
    inception:
        driver: bridge