FROM alpine:3.18

ARG DB_NAME\
    DB_USER\
    DB_PASS\
    DB_ROOT

RUN apk update && apk add --no-cache mariadb mariadb-client

EXPOSE 3306

COPY requirements/mariadb/tools/setup.sh .

RUN sh setup.sh && rm setup.sh

USER mysql

CMD ["/usr/bin/mysqld", "--skip-log-error"]