FROM alpine:3.18
RUN apk add --no-cache mariadb mariadb-client \
            mariadb-server-utils 
			#  && \
            # rm -f /var/cache/apk/*
RUN mkdir /docker-entrypoint-initdb.d && \
    mkdir /scripts/pre-exec.d && \
    mkdir /scripts/pre-init.d && \
    chmod -R 755 /scripts

ADD ./tools/setup.sh /scripts/setup.sh
RUN chmod +x /scripts/setup.sh

EXPOSE 3306


# RUN ./scripts/setup.sh

ENTRYPOINT ["/scripts/run.sh"]