FROM alpine:3.18
RUN apk add --no-cache mariadb mariadb-client \
            mariadb-server-utils 
			#  && \
            # rm -f /var/cache/apk/*
RUN mkdir -p /docker-entrypoint-initdb.d && \
    mkdir -p /scripts/pre-exec.d && \
    mkdir -p /scripts/pre-init.d  && \
    chmod -R 755 /scripts && \
    sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf && \
    sed -i "s|.*skip-networking.*|skip-networking|g" /etc/my.cnf.d/mariadb-server.cnf

ADD ./tools/setup.sh /scripts/setup.sh
RUN chmod +x /scripts/setup.sh

EXPOSE 3306


# RUN ./scripts/setup.sh

CMD ["/scripts/setup.sh"]