FROM alpine:3.18

RUN apk add --no-cache \
    php \
    php-fpm \
    php-phar \
    php-mysqli \
    php-curl \
    php-dom \
    php-exif \
    php-gd \
    php-iconv \
    php-json \
    php-fileinfo \
    php-mbstring \
    php-openssl \
    php-xml \
    php-zip\
    curl
    
# set php-fpm to listen on any address and give it root privileges 
RUN adduser -S www-data -G www-data && \
    sed -i "s|user = nobody|user = www-data|g" /etc/php81/php-fpm.d/www.conf && \
    sed -i "s|group = nobody|group = www-data|g" /etc/php81/php-fpm.d/www.conf && \
    sed -i "s|listen = 127.0.0.1:9000|listen = 9000|g" /etc/php81/php-fpm.d/www.conf && \
    sed -i "s|;listen.owner = nobody|listen.owner = www-data|g" /etc/php81/php-fpm.d/www.conf && \
    sed -i "s|;listen.group = www-data|listen.group = www-data|g" /etc/php81/php-fpm.d/www.conf

EXPOSE 9000

COPY ./requirements/wordpress/tools/ /
RUN chmod 777 setup.sh

CMD ["sh", "setup.sh"]