FROM alpine:3.18.5
RUN apk update  && \
		apk add nginx && \
		apk add openrc nginx-openrc 
# RUN # adduser -g 'Nginx www user' -h /home/www/ wwwcbz
# RUN  rc-update add nginx default
# RUN  rc-service nginx start
# https://wiki.alpinelinux.org/wiki/MariaDB