FROM alpine:3.18
RUN apk update  && apk upgrade &&  \
		apk add --no-cache nginx certbot certbot-nginx openssl
ADD requirements/nginx/tools/default.conf /etc/nginx/http.d/
ADD requirements/nginx/tools/setup.sh .
RUN chmod 777 setup.sh

EXPOSE 443
RUN ./setup.sh

CMD ["nginx", "-g", "daemon off;"]
