FROM alpine:3.18
RUN apk update  && \
		apk add --no-cache nginx certbot certbot-nginx openssl
ADD requirements/nginx/tools/default.conf /etc/nginx/http.d/
ADD requirements/nginx/tools/setup.sh .
RUN chmod +x setup.sh

EXPOSE 443

# CMD ["BASH"]
# CMD ["nginx", "-g", "daemon off;"]
CMD ["./setup.sh"]
