services:

    nginx:
            build: ./nginx/dockerfile
            ports:
                -"443:443"
            volumes:
    
    wordpress:
            build: ./wordpress/dockerfile
            ports:
                -"9000:9000"
            volumes:
            env_fie:
                - .env

    mariadb:
            build: ./mariadb/dockerfile
            env_fie:
                - .env
            ports:
                  -"3306:3306"
            volumes:        

    network:
            driver: bridge

