# version: '3.5'

# services:
#     # nginx:
#     #         build: ./nginx/dockerfile
#     #         restart: always
#     #         ports:
#     #             -"443:443"
#     #         volumes:
#     #              - wordpress_data:/var/www/html
#     wordpress:
#             build: ./wordpress/
#             restart: always
#             volumes:
#                 - wordpress_data:/var/www/html
#             ports:
#                 - 80:80
#             # secrets:
#             #     - wordpress_db_password
#             environment: 
#                 - .env  
#             network:
#                 - inception
#     mariadb:
#             build: ./mariadb/dockerfile
#             restart: always
#             environment: 
#                 - .env  
#             ports:
#                     - 3306:3306
#             network:
#                 - inception
#             volumes:
#                 - mariadb_data:/var/lib/mysql

#     network:
#         inception:
#             driver: bridge
#     volumes:
#     wordpress_data:
#         o: bind  # Use bind mount functionality
#         device: ${HOME}/data/wordpress  # Path on the host for WordPress data

#     mariadb_data:
#         o: bind  # Use bind mount functionality
#         device: ${HOME}/data/mysql  # Separate path for MariaDB data (recommended)

version: '3.5'

services:

  mariadb:
    build: ./mariadb/
    restart: always
    environment: 
      - .env  # Or define specific variables here for MariaDB
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./wordpress/
    # depends_on: mariadb
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 80:80
    # secrets:
    #   - wordpress_db_password  # Uncomment if needed
    environment:  
      - .env  # Assuming .env has variables for both services
networks:
  inception:
    driver: bridge  # Define network only once

volumes:
  wordpress_data:
    # o: bind  # Use bind mount functionality
    # device: ${HOME}/data/wordpress  # Path on the host for WordPress data

  mariadb_data:
    # o: bind  # Use bind mount functionality
    # device: ${HOME}/data/mysql  # Separate path for MariaDB data (recommended)
