# version: '3.5'

# services:
#     # nginx:
#     #         build: ./nginx/dockerfile
#     #         restart: always
#     #         ports:
#     #             -"443:443"
#     #         volumes:
#     #              - wordpress_data:/var/www/html
#     wordpress:
#             build: ./wordpress/
#             restart: always
#             volumes:
#                 - wordpress_data:/var/www/html
#             ports:
#                 - 80:80
#             # secrets:
#             #     - wordpress_db_password
#             environment: 
#                 - .env  
#             network:
#                 - inception
#     mariadb:
#             build: ./mariadb/dockerfile
#             restart: always
#             environment: 
#                 - .env  
#             ports:
#                     - 3306:3306
#             network:
#                 - inception
#             volumes:
#                 - mariadb_data:/var/lib/mysql

#     network:
#         inception:
#             driver: bridge
#     volumes:
#     wordpress_data:
#         o: bind  # Use bind mount functionality
#         device: ${HOME}/data/wordpress  # Path on the host for WordPress data

#     mariadb_data:
#         o: bind  # Use bind mount functionality
#         device: ${HOME}/data/mysql  # Separate path for MariaDB data (recommended)

version: '3'

services:
  mariadb:
    build: ./mariadb/
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./wordpress/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/
    networks:
      - inception
    env_file:
      - .env
    restart: always
  nginx:
    build: ./nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/
networks:
  inception:
    driver: bridge  # Define network only once

volumes:
  wordpress_data:
    # o: bind  # Use bind mount functionality
    # device: ${HOME}/data/wordpress  # Path on the host for WordPress data

  mariadb_data:
    # o: bind  # Use bind mount functionality
    # device: ${HOME}/data/mysql  # Separate path for MariaDB data (recommended)


# version: '3'

# services:
#   nginx:
#     build: ./nginx
#     ports:
#       - "443:443"
#     depends_on:
#       - wordpress
#     networks:
#       - inception
#     volumes:
#       - wordpress_data:/var/www/
#     restart: always
#     env_file:
#       - .env

#   mariadb:
#     build: ./mariadb
#     env_file:
#       - .env
#     container_name: mariadb
#     ports:
#       - "3306:3306"
#     networks:
#       - inception
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     restart: always

#   wordpress:
#     build: ./wordpress
#     depends_on:
#       - mariadb
#     networks:
#       - inception
#     volumes:
#       - wordpress_data:/var/www/
#     restart: always
#     env_file:
#       - .env

# volumes:
#   wordpress_data:
#     # driver_opts:
#     #   o: bind
#     #   type: none
#     #   device: ${HOME}/data/wordpress

#   mariadb_data:
#     # driver_opts:
#     #   o: bind
#     #   type: none
#     #   device: ${HOME}/data/mariadb

# networks:
#     inception:
#         driver: bridge