version: '3.1'

services:

    # nginx:
    #         build: ./nginx/dockerfile
    #         ports:
    #             -"443:443"
    #         volumes:
    #              - wordpress_data:/var/www/html
    
    wordpress:
            build: ./wordpress/dockerfile
            restart: always
            ports:
                -"8080:80"
            volumes:
                - wordpress_data:/var/www/html
            env_fie:
                - .env
            secrets:
                - wordpress_db_password

    mariadb:
            build: ./mariadb/dockerfile
            env_fie:
                - .env
            ports:
                  -"3306:3306"
            volumes:
                - mariadb_data:/var/lib/mysql       

    # network:
    #         driver: bridge
volumes:
    wordpress_data:
    mariadb_data:
