version: '3.5'

services:

    # nginx:
    #         build: ./nginx/dockerfile
    #         restart: always
    #         ports:
    #             -"443:443"
    #         volumes:
    #              - wordpress_data:/var/www/html
    
    wordpress:
            build: ./wordpress/
            restart: always
            volumes:
                - wordpress_data:/var/www/html
            ports:
                - 80:80
            # secrets:
            #     - wordpress_db_password
            environment: 
                - .env  

    # mariadb:
    #         build: ./mariadb/dockerfile
    #         restart: always
    #         env_fie:
    #             - .env
    #         ports:
    #               -3306:3306
    #         volumes:
    #             - mariadb_data:/var/lib/mysql

# network:
#         driver: bridge
volumes:
    wordpress_data:
        driver: local
#     mariadb_data:
#         driver: local

